import os
import re
import streamlit as st
from dotenv import load_dotenv
from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import TranscriptsDisabled, VideoUnavailable
import google.generativeai as genai

# Load environment variables
load_dotenv()

# Configure Google Gemini Pro API
api_key = "AIzaSyDe1-tmszp0nrSRs_Thp0b9IRrp_ni4NLQ"
genai.configure(api_key=api_key)

# Summarization prompt
PROMPT = """Welcome, Video Summarizer! Your task is to distill the essence of a given YouTube video transcript into a concise summary. 
Your summary should capture the key points and essential information, presented in bullet points, within a 250-word limit. 
Let's dive into the provided transcript and extract the vital details for our audience."""

# Function to validate YouTube URL
def is_valid_youtube_url(url):
    pattern = r"^https?://(www\.)?youtube\.com/watch\?v=.+$"
    return re.match(pattern, url) is not None

# Function to extract transcript details
def extract_transcript_details(youtube_video_url):
    try:
        video_id = youtube_video_url.split("=")[1]
        st.write(f"Extracting transcript for video ID: {video_id}")
        transcript_text = YouTubeTranscriptApi.get_transcript(video_id)
        st.write("Transcript extraction successful.")
        return " ".join([i["text"] for i in transcript_text])
    except TranscriptsDisabled:
        st.error("Transcripts are disabled for this video.")
        return "Transcripts are disabled for this video."
    except VideoUnavailable:
        st.error("The video is unavailable or invalid.")
        return "The video is unavailable or invalid."
    except Exception as e:
        st.error(f"Error during transcript extraction: {str(e)}")
        return f"An error occurred: {str(e)}"

# Function to generate summary using Google Gemini Pro
def generate_gemini_content(transcript_text, prompt):
    try:
        st.write(f"Generating summary for {len(transcript_text)} characters.")
        
        # Use the Gemini model
        model = genai.GenerativeModel("gemini-1.5-flash")
        st.write("Sending request to Google Gemini Pro...")

        # Generate content using the model
        response = model.generate_content(f"{prompt}\n{transcript_text}")
        
        # Log the response
        st.write(f"Response received from Google Gemini Pro: {response}")
        
        # Extract the generated content from the response
        if response and response.candidates:
            # Access the first candidate's generated text
            candidate = response.candidates[0]
            st.write(f"Generated content: {candidate.content.parts[0].text}")
            return candidate.content.parts[0].text
        else:
            st.error("No content was generated by the model.")
            return "No content was generated by the model."
    except Exception as e:
        st.error(f"Error generating summary with Gemini Pro: {str(e)}")
        return f"Error generating summary with Gemini Pro: {str(e)}"

# Streamlit UI
st.title("Gemini YouTube Transcript Summarizer: Extract Key Insights from YouTube Videos")
youtube_link = st.text_input("Enter YouTube Video Link:")

if youtube_link:
    if is_valid_youtube_url(youtube_link):
        video_id = youtube_link.split("=")[1]
        st.image(f"http://img.youtube.com/vi/{video_id}/0.jpg", use_column_width=True)

        if st.button("Get Detailed Notes"):
            with st.spinner("Processing..."):
                # Extract transcript
                st.write(f"Starting transcript extraction for video: {youtube_link}")
                transcript_text = extract_transcript_details(youtube_link)

                if transcript_text and not transcript_text.startswith("An error occurred"):
                    # Attempt to use Google Gemini Pro
                    if api_key:
                        st.write("Attempting to generate summary using Google Gemini Pro...")
                        summary = generate_gemini_content(transcript_text, PROMPT)
                    else:
                        summary = "No valid API key configured for Google Gemini Pro. Please check your environment variables."
                        st.error(summary)

                    # Display summary
                    st.markdown("## Detailed Notes:")
                    st.write(summary)
                else:
                    st.error(transcript_text)
    else:
        st.error("Please enter a valid YouTube video URL.")
